#!/bin/bash

# enable debug
set -x
[ -d "../vars" ] || mkdir "../vars"
git log --oneline | wc -l > ../vars/gitcount
git log -1 | head -1 | awk '{print $2}' > ../vars/gitcommit

make  DESTDIR=""  || exit 1

mkdir -p ${DESTDIR}/usr/local/opsx-demo/bin
install timeout ${DESTDIR}/usr/local/opsx-demo/bin/


